### PR TITLE
Update MatchmakingRequest.md

### PR DESCRIPTION
**Pull request by cjbonn**
Chris, Do you have an ETA on the next doc release ?

### CODE REVIEW

**Comment by chrishadfield** [comment]
Christopher,

Yes:
- Docs with updates to support Sprint 72 were released yesterday.
- Sprint 73 is currently in test and we should be releasing within 10-14 days with Doc updates.

**Comment by cjbonn** [comment]
When will GitHub have the most recent doc? Shows last update 1 month ago

**Comment by chrishadfield** [comment]
Christopher,

Checked with Dev for this missing coverage of this error code for MatchmakingRequest and will be updated for next Doc release.

Thanks!
Chris Hadfield
Tech Writer

**Comment by chrishadfield** [comment]
Not sure where you are looking:
mmakingrequestdocspage

**Comment by cjbonn** [comment]
Looking here:
https://i.gyazo.com/1ec4ab56ac66b51a4f0e98ab1f1e9b8d.png

**Comment by chrishadfield** [comment]
OK thanks.

We maintain 2 Docs sites at the moment. One for the old portal - docs.gamesparks.com - and one for our new portal - docs2.gamesparks.com. an one for that's a commit I did then to our

**Comment by cjbonn** [comment]
Ahhh so really instead of making pull requests I should be submitting helpdesk tickets instead, huh?

**Comment by chrishadfield** [comment]
If it is something concerning the content of one Doc pages - such as the pull requests you've made so far - could you please continue to submit pull requests, which I will see and act on. Alternatively, there's also a Comments section at the bottom of each Docs page (not there on section landing pages) where you can submit feedback on the content of that page.

However, if you have feedback on something directly to do with some area of the portal's funtionality, it would be better to submit a ticket to our Customer Support, rather than comment on the Docs page that covers that part of the portal.

Whichever it is, thanks again for your feedback!

**Pull request closed without merging**
